type CountryCode = string

export const COUNTRIES_MAP = new Map<CountryCode, string>([
	["AF", "Afghanistan"],
	["AL", "Albania"],
	["DZ", "Algeria"],
	["AD", "Andorra"],
	["AO", "Angola"],
	["AR", "Argentina"],
	["AM", "Armenia"],
	["AU", "Australia"],
	["AT", "Austria"],
	["AZ", "Azerbaijan"],
	["BS", "Bahamas"],
	["BD", "Bangladesh"],
	["BB", "Barbados"],
	["BY", "Belarus"],
	["BE", "Belgium"],
	["BZ", "Belize"],
	["BJ", "Benin"],
	["BM", "Bermuda"],
	["BT", "Bhutan"],
	["BO", "Bolivia"],
	["BA", "Bosnia and Herzegovina"],
	["BW", "Botswana"],
	["BR", "Brazil"],
	["BG", "Bulgaria"],
	["KH", "Cambodia"],
	["CM", "Cameroon"],
	["CA", "Canada"],
	["KY", "Cayman Islands"],
	["TD", "Chad"],
	["CL", "Chile"],
	["CN", "China"],
	["CX", "Christmas Island"],
	["CO", "Colombia"],
	["CD", "Congo"],
	["CR", "Costa Rica"],
	["HR", "Croatia"],
	["CU", "Cuba"],
	["CY", "Cyprus"],
	["CZ", "Czechia"],
	["DK", "Denmark"],
	["DJ", "Djibouti"],
	["DM", "Dominica"],
	["DO", "Dominican Republic"],
	["EC", "Ecuador"],
	["EG", "Egypt"],
	["SV", "El Salvador"],
	["EE", "Estonia"],
	["ET", "Ethiopia"],
	["FO", "Faroe Islands"],
	["FJ", "Fiji"],
	["FI", "Finland"],
	["FR", "France"],
	["GF", "French Guiana"],
	["PF", "French Polynesia"],
	["GA", "Gabon"],
	["GM", "Gambia"],
	["GE", "Georgia"],
	["DE", "Germany"],
	["GH", "Ghana"],
	["GI", "Gibraltar"],
	["GR", "Greece"],
	["GL", "Greenland"],
	["GD", "Grenada"],
	["GT", "Guatemala"],
	["GN", "Guinea"],
	["HT", "Haiti"],
	["HN", "Honduras"],
	["HK", "Hong Kong"],
	["HU", "Hungary"],
	["IS", "Iceland"],
	["IN", "India"],
	["ID", "Indonesia"],
	["IR", "Iran"],
	["IQ", "Iraq"],
	["IE", "Ireland"],
	["IT", "Italy"],
	["JM", "Jamaica"],
	["JP", "Japan"],
	["JE", "Jersey"],
	["JO", "Jordan"],
	["KZ", "Kazakhstan"],
	["KE", "Kenya"],
	["KR", "Korea"],
	["KW", "Kuwait"],
	["KG", "Kyrgyzstan"],
	["LV", "Latvia"],
	["LB", "Lebanon"],
	["LY", "Libya"],
	["LI", "Liechtenstein"],
	["LT", "Lithuania"],
	["LU", "Luxembourg"],
	["MG", "Madagascar"],
	["MY", "Malaysia"],
	["MV", "Maldives"],
	["ML", "Mali"],
	["MT", "Malta"],
	["MH", "Marshall Islands"],
	["MQ", "Martinique"],
	["MX", "Mexico"],
	["MD", "Moldova"],
	["MC", "Monaco"],
	["MN", "Mongolia"],
	["ME", "Montenegro"],
	["MA", "Morocco"],
	["MZ", "Mozambique"],
	["MM", "Myanmar"],
	["NP", "Nepal"],
	["NL", "Netherlands"],
	["NZ", "New Zealand"],
	["NI", "Nicaragua"],
	["NE", "Niger"],
	["NG", "Nigeria"],
	["NO", "Norway"],
	["PK", "Pakistan"],
	["PS", "Palestine"],
	["PA", "Panama"],
	["PG", "Papua New Guinea"],
	["PE", "Peru"],
	["PL", "Poland"],
	["PT", "Portugal"],
	["PR", "Puerto Rico"],
	["QA", "Qatar"],
	["MK", "Republic of North Macedonia"],
	["RO", "Romania"],
	["RU", "Russian Federation"],
	["RW", "Rwanda"],
	["SA", "Saudi Arabia"],
	["SN", "Senegal"],
	["RS", "Serbia"],
	["SG", "Singapore"],
	["SK", "Slovakia"],
	["SI", "Slovenia"],
])
