services:
  caddy:
    image: caddy:2.10-alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./dist:/srv
      - caddy_data:/data
      - caddy_config:/config

  # Golang backend set-up.
  backend:
    image: ghcr.io/mattismoel/konnekt-backend:${BRANCH:-main}
    restart: unless-stopped
    environment:
      - DB_DIR=${DB_DIR:-/app/data}
      - DB_FILE_NAME=${DB_FILE_NAME:-data.db} 
      - ORIGIN=${ORIGIN:-http://localhost:4000}
    volumes:
      - ${DB_LOCAL_DIR:-./data}:${DB_DIR:-/app/data}
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/health"]
      interval: 60s
      timeout: 5s
      retries: 5

volumes:
  caddy_data:
  caddy_config:
