services:
  frontend:
    image: oven/bun:1
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: sh -c "bun install && bun run dev -- --host 0.0.0.0"
    ports:
      - 3000:3000
    environment:
    - NODE_ENV=development

  backend:
    image: golang:1.24
    working_dir: /app
    volumes:
      - ./backend:/app
      - ~/.aws:/root/.aws:ro"
    command: sh -c "go mod tidy && go install github.com/air-verse/air@latest && air"
    ports:
      - 8080:8080
  caddy:
    image: caddy:latest
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
    - ./Caddyfile.dev:/etc/caddy/Caddyfile
    depends_on:
      - frontend
      - backend
