services:
  web_server:
    image: ghcr.io/mattismoel/konnekt/konnekt-web-server:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - caddy_data:/data
      - caddy_config:/config
  backend:
    image: ghcr.io/mattismoel/konnekt/konnekt-backend:main
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      - AWS_SHARED_CREDENTIALS_FILE=/app/aws/credentials
      - DB_DIR=${DB_DIR:-/app/data}
      - DB_FILE_NAME=${DB_FILE_NAME:-data.db}
      - ORIGIN=${ORIGIN:-https://knnkt.dk}
    volumes:
      - db_data:/app/data
      - aws:/app/aws
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/health"]
      interval: 60s
      timeout: 5s
      retries: 5

volumes:
  db_data:
  aws:
  caddy_data:
  caddy_config:
