services:
  frontend:
    image: oven/bun:1
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: sh -c "bun install && bun run dev -- --host 0.0.0.0"
    ports:
      - 5173:5173
    environment:
      - NODE_ENV=development
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/pb/pb_data:/pb/pb_data
      - ./backend/pb/pb_migrations:/pb/pb_migrations
    ports:
      - 8080:8080
  caddy:
    image: caddy:latest
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - ./Caddyfile.dev:/etc/caddy/Caddyfile
    depends_on:
      - frontend
      - backend

volumes:
  pb_data:
  node_modules:
