services:
  backend:
    image: ghcr.io/mattismoel/konnekt-backend:main
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      - DB_DIR=${DB_DIR:-/app/data}
      - DB_FILE_NAME=${DB_FILE_NAME:-data.db} 
      - ORIGIN=${ORIGIN:-http://localhost:4000}
    volumes:
      - db_data:/app/data
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/health"]
      interval: 60s
      timeout: 5s
      retries: 5

volumes:
  db_data:
