name: Backend

env:
  REGISTRY: ghcr.io
  PACKAGE_NAME: konnekt-backend

on:
  pull_request:
    branches: [ "main" ]
    paths:
    - 'backend/**'
  push:
    branches: [ "main" ]
    paths:
    - 'backend/**'

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
    - uses: actions/checkout@v4

    - name: Setup up Go
      uses: actions/setup-go@v4

    - name: Format
      run: gofmt -s -w . && git diff --exit-code

    - name: Tidy
      run: go mod tidy && git diff --exit-code

    - name: Vet
      run: go vet ./...

    - name: Test
      run: go test -v -count=1 -race -shuffle=on ./...

  publish-webserver:
    needs: test-and-build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.actor }}/${{ github.event.repository.name }}/${{ env.PACKAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ github.actor }}/${{ github.event.repository.name }}/${{ env.PACKAGE_NAME }}:${{ github.sha }}
