name: Test Backend

on:
  pull_request:
    branches: [ "main" ]
    paths:
    - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
    - uses: actions/checkout@v4

    - name: Setup up Go
      uses: actions/setup-go@v4

    - name: Format
      run: gofmt -s -w . && git diff --exit-code

    - name: Tidy
      run: go mod tidy && git diff --exit-code

    - name: Vet
      run: go vet ./...

    - name: Mod mod download
      run: go mod download

    - name: Build
      run: go build -o /dev/null -v ./...

    - name: Test
      run: go test -v -count=1 -race -shuffle=on ./...
